server:
  port: 8080
spring:
  application:
    name: redisTemplate
  datasource:
    url: localhost:3306
    username: root
    password: root
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
        max-active: 8
schedules:
        0/5 * * * * ?
cron:
    1000
#    lettuce:
#      pool:
#        max-active: 8 # 连接池最大连接数(使用负值表示没有限制) 默认为8
#        max-wait: -1ms # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
#        max-idle: 8 # 连接池中的最大空闲连接 默认为8
#        min-idle: 0 # 连接池中的最小空闲连接 默认为 0


